import asyncio
import json
import logging

from fastapi import APIRouter, Depends, HTTPException, Query, Request
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session
from sse_starlette.sse import EventSourceResponse

from instilens.ai import build_engine
from instilens.api.deps import current_user, get_session, require_admin, ticket_user
from instilens.api.hardening import client_ip, hit
from instilens.config import settings
from instilens.db.session import session_scope
from instilens.domain.models import User
from instilens.services import analytics

log = logging.getLogger("instilens.api")

# Every data route requires a signed-in user; /auth/* and /health live outside this router.
router = APIRouter(prefix="/api/v1", tags=["intelligence"], dependencies=[Depends(current_user)])
# Routes a browser reaches without headers (EventSource, <audio>): authenticated by a short-lived ticket instead.
ticket_router = APIRouter(prefix="/api/v1", tags=["intelligence"])


def _ai_budget(request: Request, user: User) -> None:
    """Paid model calls: per-user hourly cap (ASVS 7.17 — expensive endpoints get their own budget)."""
    if not hit(f"ai:{user.id}", settings.ai_requests_per_hour, 3600):
        raise HTTPException(429, "AI request budget exhausted for this hour", headers={"Retry-After": "3600"})
    log.info("ai call user=%s ip=%s path=%s", user.id, client_ip(request), request.url.path)

MarketParam = Query("TR", pattern="^(TR|US)$")
LangParam = Query("tr", pattern="^(tr|en)$")


@router.get("/radar")
def get_radar(market: str = MarketParam, limit: int = Query(20, ge=1, le=100), window: int | None = Query(None, ge=1, le=365), session: Session = Depends(get_session)):
    """Default window = the market's score window (TR 30D, US 100D). Other windows re-aggregate flows on the fly."""
    data = analytics.radar(session, market, limit)
    if window is not None and window != data.get("window_days"):
        flows = analytics.window_flows(session, market, window)
        data.update({"window_days": window, "window_start": flows["window_start"], "accumulated": flows["accumulated"][:limit], "distributed": flows["distributed"][:limit]})
    return data


@router.get("/news")
def get_news(market: str = MarketParam, symbol: str | None = Query(None, max_length=16), limit: int = Query(40, ge=1, le=200), session: Session = Depends(get_session)):
    return analytics.news(session, market, symbol, limit)


@router.get("/freshness")
def get_freshness(market: str = MarketParam, session: Session = Depends(get_session)):
    return analytics.data_freshness(session, market)


@router.get("/signals/performance")
def get_signal_performance(market: str = MarketParam, session: Session = Depends(get_session)):
    return analytics.signal_performance(session, market)


@router.get("/institutions")
def get_institutions(market: str = MarketParam, session: Session = Depends(get_session)):
    return analytics.institutions(session, market)


@router.get("/institutions/{code}")
def get_institution(code: str, market: str = MarketParam, session: Session = Depends(get_session)):
    data = analytics.institution_detail(session, market, code)
    if data is None:
        raise HTTPException(404, "institution not found")
    return data


@router.get("/funds/{code}/compare/{other}")
def get_fund_compare(code: str, other: str, session: Session = Depends(get_session)):
    data = analytics.compare_funds(session, code, other)
    if data is None:
        raise HTTPException(404, "fund not found")
    return data


@router.get("/stocks/{symbol}")
def get_stock(symbol: str, market: str = MarketParam, session: Session = Depends(get_session)):
    data = analytics.stock_detail(session, market, symbol)
    if data is None:
        raise HTTPException(404, "instrument not found")
    return data


@router.get("/stocks/{symbol}/ai")
def get_stock_ai(symbol: str, request: Request, market: str = MarketParam, refresh: bool = False, lang: str = LangParam, user: User = Depends(current_user), session: Session = Depends(get_session)):
    """AI note for the stock (flows × headlines). Cached per day and language; refresh=true (admin) regenerates."""
    from instilens.ai.assess import AiUnavailable, note_json, stock_assessment

    if refresh:
        require_admin(user)
        _ai_budget(request, user)
    try:
        note = stock_assessment(session, market, symbol, force=refresh, lang=lang)
    except AiUnavailable as exc:
        raise HTTPException(503, f"ai unavailable: {exc}") from exc
    if note is None:
        raise HTTPException(404, "no assessment available (unknown symbol or AI disabled)")
    return note_json(note)


@router.get("/brief")
def get_brief(request: Request, market: str = MarketParam, refresh: bool = False, lang: str = LangParam, user: User = Depends(current_user), session: Session = Depends(get_session)):
    """Morning brief for the market. Generated by the scheduler at 08:30 (TR + EN); refresh=true (admin) regenerates now."""
    from instilens.ai.assess import AiUnavailable, daily_brief, note_json

    if refresh:
        require_admin(user)
        _ai_budget(request, user)
    try:
        note = daily_brief(session, market, force=refresh, lang=lang)
    except AiUnavailable as exc:
        raise HTTPException(503, f"ai unavailable: {exc}") from exc
    return note_json(note)


@ticket_router.get("/ai-notes/{note_id}/audio")
def get_note_audio(note_id: int, gender: str = Query("female", pattern="^(female|male)$"), voice: str | None = Query(None, max_length=64), user: User = Depends(ticket_user), session: Session = Depends(get_session)):
    """MP3 narration of an AI note. Voice follows the note's language and the chosen gender."""
    from fastapi.responses import FileResponse

    from instilens.ai.tts import note_text, synthesize, voice_allowed
    from instilens.domain.models import AiNote

    note = session.get(AiNote, note_id)
    if note is None:
        raise HTTPException(404, "note not found")
    if voice and not voice_allowed(note.lang, voice):
        raise HTTPException(400, "voice not available for this language")
    path = synthesize(note_text(note, session), lang=note.lang, gender=gender, voice_id=voice)
    if path is None:
        raise HTTPException(404, "tts not configured")
    return FileResponse(path, media_type="audio/mpeg", filename=f"instilens-{note.kind.lower()}-{note.as_of}.mp3")


@router.get("/tts/status")
def tts_status():
    from instilens.ai.tts import provider

    return {"provider": provider()}


@router.get("/tts/voices")
def tts_voices(lang: str = LangParam):
    """Selectable narration voices for a language (configured + admin extras + verified library voices)."""
    from instilens.ai.tts import provider, voices

    return {"provider": provider(), "lang": lang, "voices": voices(lang) if provider() == "elevenlabs" else []}


@router.get("/stocks/{symbol}/timeline")
def get_stock_timeline(symbol: str, market: str = MarketParam, session: Session = Depends(get_session)):
    data = analytics.stock_timeline(session, market, symbol)
    if data is None:
        raise HTTPException(404, "instrument not found")
    return data


@router.get("/stocks/{symbol}/series")
def get_stock_series(symbol: str, market: str = MarketParam, session: Session = Depends(get_session)):
    data = analytics.stock_series(session, market, symbol)
    if data is None:
        raise HTTPException(404, "instrument not found")
    return data


@router.get("/funds/{code}")
def get_fund(code: str, session: Session = Depends(get_session)):
    data = analytics.fund_detail(session, code)
    if data is None:
        raise HTTPException(404, "fund not found")
    return data


@router.get("/events")
def get_events(market: str = MarketParam, limit: int = Query(50, ge=1, le=200), session: Session = Depends(get_session)):
    return analytics.events(session, market, limit)


@ticket_router.get("/events/stream")
async def stream_events(market: str = MarketParam, poll_seconds: float = Query(5.0, ge=2.0, le=60.0), user: User = Depends(ticket_user)):
    """Live KAP Radar feed. SSE + DB polling is enough for the MVP; no websockets needed."""

    async def generator():
        last_id = 0
        with session_scope() as session:
            latest = analytics.events(session, market, limit=1)
            last_id = latest[0]["id"] if latest else 0
        yield {"event": "ready", "data": json.dumps({"last_id": last_id})}  # flushes headers through proxies
        while True:
            with session_scope() as session:
                fresh = analytics.events(session, market, limit=100, after_id=last_id)
            for ev in fresh:
                last_id = max(last_id, ev["id"])
                yield {"event": "transaction", "data": json.dumps(ev)}
            await asyncio.sleep(poll_seconds)

    return EventSourceResponse(generator())


@router.get("/search")
def get_search(q: str = Query("", max_length=64), market: str = MarketParam, session: Session = Depends(get_session)):
    """Header typeahead: stocks, funds and institutions of the selected market."""
    return analytics.search(session, market, q)


@router.get("/screener")
def get_screener(
    market: str = MarketParam,
    min_smart_money_score: float | None = None,
    min_consensus_score: float | None = None,
    min_funds_increasing: int | None = None,
    min_funds_new: int | None = None,
    min_net_flow_value: float | None = None,
    max_price_change_30d_pct: float | None = None,
    signal: list[str] | None = Query(None),
    limit: int = Query(25, ge=1, le=200),
    session: Session = Depends(get_session),
):
    return analytics.screener(
        session,
        market,
        min_smart_money_score=min_smart_money_score,
        min_consensus_score=min_consensus_score,
        min_funds_increasing=min_funds_increasing,
        min_funds_new=min_funds_new,
        min_net_flow_value=min_net_flow_value,
        max_price_change_pct=max_price_change_30d_pct,
        signal_types=signal,
        limit=limit,
    )


class ResearchRequest(BaseModel):
    question: str = Field(min_length=3, max_length=2000)
    market: str = Field("TR", pattern="^(TR|US)$")


@router.post("/research")
def post_research(body: ResearchRequest, request: Request, user: User = Depends(current_user), session: Session = Depends(get_session)):
    """AI research: natural-language question → tool-grounded answer with an audit trail. Per-user hourly budget."""
    _ai_budget(request, user)
    answer = build_engine(session).ask(body.question, body.market)
    return {
        "question": answer.question,
        "answer": answer.answer,
        "model": answer.model,
        "usage": answer.usage,
        "tool_calls": [{"name": c.name, "input": c.input, "output_preview": c.output_preview} for c in answer.tool_calls],
    }
