"""user webhook endpoints and durable delivery log

Revision ID: 053423e43464
Revises: b4c5d6e7f8a9
Create Date: 2026-10-02 01:25:34.636417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053423e43464'
down_revision: Union[str, Sequence[str], None] = 'b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=True),
    sa.Column('secret_seed', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_owner_id'), ['owner_id'], unique=False)

    op.create_table('webhook_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('lease_token', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_id', 'direction', 'external_id')
    )
    with op.batch_alter_table('webhook_messages', schema=None) as batch_op:
        batch_op.create_index('ix_webhook_messages_dispatch', ['status', 'next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_messages_endpoint_id'), ['endpoint_id'], unique=False)

    op.create_table('webhook_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['webhook_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_attempts_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_attempts_message_id'))

    op.drop_table('webhook_attempts')
    with op.batch_alter_table('webhook_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_messages_endpoint_id'))
        batch_op.drop_index('ix_webhook_messages_dispatch')

    op.drop_table('webhook_messages')
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_owner_id'))

    op.drop_table('webhook_endpoints')
    # ### end Alembic commands ###
