"""notification delivery prefs

Revision ID: 13f42bcd637c
Revises: 863cb204fc5b
Create Date: 2026-09-16 12:19:04.544580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f42bcd637c'
down_revision: Union[str, Sequence[str], None] = '863cb204fc5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_email', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('notify_telegram_chat_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('notify_brief', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notify_brief')
        batch_op.drop_column('notify_telegram_chat_id')
        batch_op.drop_column('notify_email')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('delivered_at')

    # ### end Alembic commands ###
