"""news items

Revision ID: 4b60fbea0b5d
Revises: 4e5742e86949
Create Date: 2026-09-16 10:26:13.726121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b60fbea0b5d'
down_revision: Union[str, Sequence[str], None] = '4e5742e86949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_code', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_code'], ['markets.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_items_market_code'), ['market_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_source'))
        batch_op.drop_index(batch_op.f('ix_news_items_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_items_market_code'))

    op.drop_table('news_items')
    # ### end Alembic commands ###
