"""user role, instrument cusip

Revision ID: 4e5742e86949
Revises: dfe6bd95b569
Create Date: 2026-09-15 01:09:04.712046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5742e86949'
down_revision: Union[str, Sequence[str], None] = 'dfe6bd95b569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cusip', sa.String(length=9), nullable=True))
        batch_op.create_index(batch_op.f('ix_instruments_cusip'), ['cusip'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=16), nullable=False, server_default='USER'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_cusip'))
        batch_op.drop_column('cusip')

    # ### end Alembic commands ###
