"""news rules and ai tags

Revision ID: 8393e4a1e2e4
Revises: 4b60fbea0b5d
Create Date: 2026-09-16 11:50:29.195701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8393e4a1e2e4'
down_revision: Union[str, Sequence[str], None] = '4b60fbea0b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('market_code', sa.String(length=8), nullable=False),
    sa.Column('query', sa.String(length=512), nullable=False),
    sa.Column('exclusion', sa.String(length=512), nullable=False),
    sa.Column('only_sources', sa.String(length=512), nullable=False),
    sa.Column('remove_sources', sa.String(length=512), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('max_age_days', sa.Integer(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('newsapi_query', sa.String(length=256), nullable=False),
    sa.Column('ai_summary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_code'], ['markets.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('ai', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_column('ai')
        batch_op.drop_column('tags')

    op.drop_table('news_rules')
    # ### end Alembic commands ###
