"""ai notes

Revision ID: 863cb204fc5b
Revises: 8393e4a1e2e4
Create Date: 2026-09-16 12:03:46.729768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863cb204fc5b'
down_revision: Union[str, Sequence[str], None] = '8393e4a1e2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('market_code', sa.String(length=8), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_code'], ['markets.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'market_code', 'subject', 'as_of')
    )
    with op.batch_alter_table('ai_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_notes_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_notes_kind'), ['kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_notes_kind'))
        batch_op.drop_index(batch_op.f('ix_ai_notes_as_of'))

    op.drop_table('ai_notes')
    # ### end Alembic commands ###
