"""initial schema

Revision ID: dfe6bd95b569
Revises: 
Create Date: 2026-09-14 23:22:15.376622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe6bd95b569'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlists_owner_id'), ['owner_id'], unique=False)

    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_code', sa.String(length=8), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=64), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['market_code'], ['markets.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_code', 'code')
    )
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutions_source_ref'), ['source_ref'], unique=False)

    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_code', sa.String(length=8), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['market_code'], ['markets.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_code', 'symbol')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_symbol'), ['symbol'], unique=False)

    op.create_table('disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_code', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('raw_uri', sa.String(length=512), nullable=True),
    sa.Column('raw_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('is_superseded', sa.Boolean(), nullable=False),
    sa.Column('parse_status', sa.String(length=16), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['market_code'], ['markets.code'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['disclosures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id')
    )
    with op.batch_alter_table('disclosures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disclosures_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_disclosures_parse_status'), ['parse_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_disclosures_published_at'), ['published_at'], unique=False)

    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('fund_type', sa.String(length=64), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('market_prices',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'trade_date')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('fund_id', sa.Integer(), nullable=True),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_owner_id'), ['owner_id'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosures.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'as_of')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_fund_id'), ['fund_id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=True),
    sa.Column('score_type', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('adjusted_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'fund_id', 'score_type', 'as_of')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_score_type'), ['score_type'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_code', sa.String(length=8), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(length=32), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['market_code'], ['markets.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'fund_id', 'signal_type', 'window_end')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_signal_type'), ['signal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_window_end'), ['window_end'], unique=False)

    op.create_table('transaction_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=False),
    sa.Column('market_code', sa.String(length=8), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('buy_nominal', sa.BigInteger(), nullable=False),
    sa.Column('sell_nominal', sa.BigInteger(), nullable=False),
    sa.Column('net_nominal', sa.BigInteger(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('net_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('ownership_before_pct', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('ownership_after_pct', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('is_superseded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosures.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['market_code'], ['markets.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_events_disclosure_id'), ['disclosure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_events_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_events_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_events_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_events_published_at'), ['published_at'], unique=False)

    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('fund_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_items_watchlist_id'), ['watchlist_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('alert_rule_id', sa.Integer(), nullable=True),
    sa.Column('dedup_key', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'dedup_key')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_owner_id'), ['owner_id'], unique=False)

    op.create_table('position_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('from_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('to_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('from_qty', sa.BigInteger(), nullable=False),
    sa.Column('to_qty', sa.BigInteger(), nullable=False),
    sa.Column('delta_qty', sa.BigInteger(), nullable=False),
    sa.Column('from_weight_pct', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('to_weight_pct', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('delta_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('activity', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['from_snapshot_id'], ['portfolio_snapshots.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['to_snapshot_id'], ['portfolio_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'instrument_id', 'to_snapshot_id')
    )
    with op.batch_alter_table('position_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_changes_activity'), ['activity'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_changes_fund_id'), ['fund_id'], unique=False)
        batch_op.create_index('ix_position_changes_instrument_period', ['instrument_id', 'period_end'], unique=False)

    op.create_table('signal_outcomes',
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('price_at_signal', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('ret_7d', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('ret_30d', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('ret_90d', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('max_return', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_table('snapshot_holdings',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('weight_pct', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['portfolio_snapshots.id'], ),
    sa.PrimaryKeyConstraint('snapshot_id', 'instrument_id')
    )
    op.create_table('transaction_event_funds',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('allocated_nominal', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['transaction_events.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'fund_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_event_funds')
    op.drop_table('snapshot_holdings')
    op.drop_table('signal_outcomes')
    with op.batch_alter_table('position_changes', schema=None) as batch_op:
        batch_op.drop_index('ix_position_changes_instrument_period')
        batch_op.drop_index(batch_op.f('ix_position_changes_fund_id'))
        batch_op.drop_index(batch_op.f('ix_position_changes_activity'))

    op.drop_table('position_changes')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_owner_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_items_watchlist_id'))

    op.drop_table('watchlist_items')
    with op.batch_alter_table('transaction_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_events_published_at'))
        batch_op.drop_index(batch_op.f('ix_transaction_events_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_events_institution_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_events_effective_date'))
        batch_op.drop_index(batch_op.f('ix_transaction_events_disclosure_id'))

    op.drop_table('transaction_events')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_window_end'))
        batch_op.drop_index(batch_op.f('ix_signals_signal_type'))
        batch_op.drop_index(batch_op.f('ix_signals_instrument_id'))

    op.drop_table('signals')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_score_type'))
        batch_op.drop_index(batch_op.f('ix_scores_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_scores_as_of'))

    op.drop_table('scores')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_fund_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_as_of'))

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_owner_id'))

    op.drop_table('alert_rules')
    op.drop_table('market_prices')
    op.drop_table('funds')
    with op.batch_alter_table('disclosures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disclosures_published_at'))
        batch_op.drop_index(batch_op.f('ix_disclosures_parse_status'))
        batch_op.drop_index(batch_op.f('ix_disclosures_kind'))

    op.drop_table('disclosures')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_symbol'))

    op.drop_table('instruments')
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_source_ref'))

    op.drop_table('institutions')
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlists_owner_id'))

    op.drop_table('watchlists')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('markets')
    # ### end Alembic commands ###
